name: sync-wheel-to-s3

on: push

jobs:
  job_1:
    name: Create Wheel
    runs-on: ubuntu-18.04
    steps:
      - shell: bash
        run: python2 -m pip wheel requests==2.14.0 
      - name: Upload wheel file
        uses: actions/upload-artifact@v1
        with:
          name: ../build/
          path: ../build/
