name: sync-wheel-to-s3

on: push

jobs:
  create_wheel_file:
    name: Create Wheel
    runs-on: ubuntu-18.04
    steps:
      run: |
          pip wheel requests==2.14.0 
    - name: Upload wheel file
        uses: actions/upload-artifact@v1
        with:
          name: requests
          path: build/
