name: sync-wheel-to-s3

on: push

jobs:
  job_1:
    name: Create Wheel
    runs-on: ubuntu-18.04
    steps:
      - shell: bash
        run: python2 -m pip wheel requests==2.14.0 
      - name: Upload wheel file
        uses: actions/upload-artifact@v1
        with:
          name: wheel_file
          path: ./

  job_2:
    name: Upload to S3 bucket
    needs: job_1
    runs-on: ubuntu-18.04
    steps:
        - name: Configure AWS Credentials
          uses: aws-actions/configure-aws-credentials@v1
          with:
            aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
            aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
            aws-region: ap-south-1
    # name: Upload to S3
    # runs-on: ubuntu-18.04
    # steps:
    #   - shell: bash
    #     run: 